name: Build RedPill DSM loader (support 7.1 Critical Update pat)

on: 
  workflow_dispatch:
    inputs:
      dsmodel:
        description: 'Input Full DSM model [DS3622xs+|DS918+|DS920+|DS923+|DS1621+]'
        required: true
        default: 'DS920+'
      major:
        description: 'Input DSM Version (ex: 7.1.0-42661-1)'
        required: true
        default: '7.1.1-42962'
      system:
        description: 'Input vm or real or test'
        required: true
        default: 'vm'
      junmod:
        description: 'Use Jun method?'
        required: true
        default: 'yes'
jobs:
  redpill:
    runs-on: ubuntu-latest
    name: Build RedPill lkm and load
    steps:
      - uses: actions/checkout@v2.1.0
        name: checkout src
        id: checkout
        with:
          submodules: 'true'
      - name: Build dsm 7.1
        id: build-dsm-71
        run: |
            bash build-universal-update.sh ${{github.event.inputs.dsmodel}} ${{github.event.inputs.major}} ${{github.event.inputs.system}} ${{github.event.inputs.junmod}}
      - name: Archive loader image
        uses: actions/upload-artifact@v2
        with:
          name: redpill-${{github.event.inputs.dsmodel}}_${{github.event.inputs.major}}-loader
          path: output/
